version: '3.8'

services:
  mongo:
    image: mongo:6.0.9
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/coder-fernandes
      - JWT_SECRET=change-me
    depends_on:
      - mongo

volumes:
  mongo-data:
